name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions:
      contents: write
    # --- END OF ADDITION ---

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build the executable
        run: go build -v -o cowrie-graph ./cmd/web

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: cowrie-graph